### ISSUE TITLE
缺少文件ResultActivity.

### ISSUE THREAD

**Issue by fangaofeng** [5peak2me/QRCode#3]
E:\AndroidStudioProjects\QRCode-master\zxing-demo-2\src\com\google\zxing\activity\CaptureActivity.java:54: error: cannot find symbol
import com.jinlin.zxing.example.ResultActivity;
                               ^
  symbol:   class ResultActivity
  location: package com.jinlin.zxing.example
E:\AndroidStudioProjects\QRCode-master\zxing-demo-2\src\com\google\zxing\activity\CaptureActivity.java:264: error: cannot find symbol
        startActivity(new Intent(CaptureActivity.this, ResultActivity.class).putExtras(bundle));
                                                       ^
  symbol:   class ResultActivity
  location: class CaptureActivity
2 errors

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':zxing-demo-2:compileDebugJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by MyBadBoy** [comment]
确实存在该问题~可以

**Comment by 5peak2me** [comment]
@MyBadBoy @fangaofeng 你好，项目已经修复。多谢反馈
